 # Linear Algebra Fundamentals

## Dot Product and finding angles between vectors.

The following is a function used to find the angle between two n-dimensional vectors using the formula v . w = abcos(θ).

In [1]:
# Imports 
import numpy as np
from numpy import arccos, dot
from numpy.linalg import norm

# Function for finding angle between two vectors v and w
def anglebetweenvector(v,w):
  theta = arccos(dot(v, w.T)/(norm(v) * norm(w)))
  return theta

Finding the angle between vectors <1,0,0> and <0,1,0>. This, as we know, should result in an angle of pi/2 ≈ 1.57079632679

In [2]:
# Defining vectors
v = np.array([1,0,0])
w = np.array([0,1,0])

# Finding angle between vectors
print(anglebetweenvector(v,w))

1.5707963267948966


## Cross-Product

Below is a function for finding the cross product between two vectors v and w

In [3]:
# Defining vectors
v = np.array([1,0,0])
w = np.array([0,1,0])

# Finding the cross-product of v and w
print(np.cross(v,w))

[0 0 1]


## Determinant

The following is a program used to find the determinant of a matrix which gives information on how a linear transformation scales.

In [4]:
# Imports
from numpy.linalg import det

# Defining matrix M
M = np.array([[0,1,2,3],
              [4,5,6,7],
              [8,9,10,11],
              [12,13,14,15]])

# Outputting the matrix and the determinant
print("Matrix M \n", M)
print("Determinant: ", det(M))

Matrix M 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Determinant:  0.0


Therefore, the above matrix is singular.

## Solving Systems of Linear Equations

The following is a a short program for solving a system of linear equations. In this example we will solve  the system: -2x+y=-1 and x+y=2. Solving algebraically we get (1,1). The following is using a rref approach.

In [5]:
# Creating a Coefficent matrix
M = np.array([[-2,1],
              [1,1,]])
y = np.array([-1,2])

# Solving Linear System
intersection = np.linalg.solve(M,y)
print(intersection)

[1. 1.]
